### ISSUE TITLE
Add support for encrypted credentials into a separate creds file

### ISSUE THREAD

**Issue by fbordenave** [percona/pxc_scheduler_handler#32]
Please add support to store the user/pwd credentials in a credentials files so we can encrypt this information instead of using it as plain text into the main config file.

**Comment by Oneiroi** [comment]
1. encryption should be reverse able
2. encryption key should be set in configuration file (avoids static keys and key re-use attacks)
3. failure to decrypt should abort the process and logout the reason for doing so (fail-closed)
4. future option to re-write config if not encrypted with encrypted strings (optional)

**Comment by Tusamarco** [comment]
After few discussion this feature may sound redundant. The main point is that we already have the same username/password pair in clear text in several places like proxysql.cnf or in the global variables.
To enforce security is enough to give the right authorization at the config file (i.e. 600 to proxysql user) as is done for ssh keys. 
Adding an encryption mechanism is just adding another layer of complexity and will require anyhow a place where to store the keys. 
So no reason to proceed here, just use the right settings when assigning the config file.
