### ISSUE TITLE
Remove lock file after a given time 

### ISSUE THREAD

**Issue by Tusamarco** [percona/pxc_scheduler_handler#39]
The lock file is created to prevent parallel run when the pxc_scheduler_handler is executed inside proxysql. But it may happen that a lock file remain in the file system and that prevents the scheduler to run.
At the moment an error message is written in the log, but it may be helpful to add a functionality that removes the scheduler after a given time (like 1 minute). We can also add a check to see if the PID reported is not existing or still running

**Comment by dblore** [comment]
Hey @Tusamarco, any plans to pick this one up? We recently ran into this when the scheduler was OOM killed (by no fault of its own), but we had a stuck lock file until manually cleaned up.
