### ISSUE TITLE
pxc_scheduler_handler doesn't honor the failBack=false , if mysql_galera_hostgroups configured with PXC nodes.

### ISSUE THREAD

**Issue by ricksunil** [percona/pxc_scheduler_handler#40]
Hello,
pxc_scheduler_handler doesn't honor the failBack=false , if mysql_galera_hostgroups configured.
Also, there is nothing mentioned that mysql_galera_hostgroup  table in ProxySQL should be empty to work properly in documentattion.
How To reproduce:
INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight,max_connections,comment) VALUES ('192.168.70.10',100,3306,1000,2000,'Preferred writer');
INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight,max_connections,comment) VALUES ('192.168.70.20',100,3306,999,2000,'Second preferred ');
INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight,max_connections,comment) VALUES ('192.168.70.30',100,3306,998,2000,'Las chance');
INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight,max_connections,comment) VALUES ('192.168.70.10',101,3306,998,2000,'last reader');
INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight,max_connections,comment) VALUES ('192.168.70.20',101,3306,1000,2000,'reader1');    
INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight,max_connections,comment) VALUES ('192.168.70.30',101,3306,1000,2000,'reader2');        
INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight,max_connections,comment) VALUES ('192.168.70.10',8100,3306,1000,2000,'Failover server preferred');
INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight,max_connections,comment) VALUES ('192.168.70.20',8100,3306,999,2000,'Second preferred');    
INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight,max_connections,comment) VALUES ('192.168.70.30',8100,3306,998,2000,'Thirdh and last in the list');      
INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight,max_connections,comment) VALUES ('192.168.70.10',8101,3306,998,2000,'Failover server preferred');
INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight,max_connections,comment) VALUES ('192.168.70.20',8101,3306,999,2000,'Second preferred');    
INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight,max_connections,comment) VALUES ('192.168.70.30',8101,3306,1000,2000,'Thirdh and last in the list');
LOAD MYSQL SERVERS TO RUNTIME; SAVE MYSQL SERVERS TO DISK; 

mysql_galera_hostgroups  table:
INSERT INTO mysql_galera_hostgroups (writer_hostgroup,backup_writer_hostgroup,reader_hostgroup,offline_hostgroup,active,max_writers,writer_is_also_reader,max_transactions_behind) 
VALUES (100,200,101,300,1,1,0,100);
INSERT INTO mysql_galera_hostgroups (writer_hostgroup,backup_writer_hostgroup,reader_hostgroup,offline_hostgroup,active,max_writers,writer_is_also_reader,max_transactions_behind) 
VALUES (8100,8200,8101,8300,1,1,0,100);
load mysql servers to runtime;save mysql servers to disk;

Scheduler table:
INSERT  INTO scheduler (id,active,interval_ms,filename,arg1,arg2) values (10,1,2000,"/var/lib/proxysql/pxc_scheduler_handler","--configfile=config.toml","--configpath=/var/lib/proxysql");
LOAD SCHEDULER TO RUNTIME;SAVE SCHEDULER TO DISK;

Solutions: pxc scheduler should be in the inactive state and print this as an error.

Please mention in documentation, mysql_galera_hostgroups table should be empty to work properly.

Thanks,
Sunil

**Comment by Tusamarco** [comment]
Ok @ricksunil  as discussed yesterday I agree to raise an error and stop the execution if there is native galera active.
So the actions will be:

- quick fix, add a note to the documentation
- add check code (in the sanity check step) to prevent to have the pxc_scheduler_handler running if there is native galera support.

Anyhow let me underline, that is NOT the pxc_scheduler_handler that is not honoring the failback option, but the fact you have active the native galera support that conflict with the pxc_scheduler_handler execution.
thanks to raise the issue.

**Comment by Tusamarco** [comment]
Documentation is updated.

**Comment by Tusamarco** [comment]
release v1.3.1 has all latest fix
