### ISSUE TITLE
Tag ERROR for permission denied messages on config.toml  

### ISSUE THREAD

**Issue by garruti9** [percona/pxc_scheduler_handler#41]
Hi all,
When configuring  pxc_scheduler_handler on ProxySQL with wrong permissions in **config.toml** file, the following messages are shown in the **proxysql.log** file:

`open /var/lib/proxysql/proxysql_scheduler/config/config.toml: permission denied
  open /var/lib/proxysql/proxysql_scheduler/config/config.toml: permission denied
  open /var/lib/proxysql/proxysql_scheduler/config/config.toml: permission denied
  open /var/lib/proxysql/proxysql_scheduler/config/config.toml: permission denied
`

However, other permission denied errors are logged with the [ERROR] tag:

`
[ERROR]:2021-11-10 14:45:26 - Error logging to file open /var/log/pscheduler.log: permission denied
[ERROR]:2021-11-10 14:45:28 - Error logging to file open /var/log/pscheduler.log: permission denied
[ERROR]:2021-11-10 14:45:30 - Error logging to file open /var/log/pscheduler.log: permission denied
[ERROR]:2021-11-10 14:45:32 - Error logging to file open /var/log/pscheduler.log: permission denied
`

In order to improve debugging, it would be useful that all the permission denied messages are logged with the [ERROR] tag.

Thanks!

**Comment by Tusamarco** [comment]
@garruti9 ok already added to the current push .. so it will be available next bug release in short

**Comment by Tusamarco** [comment]
done v1.3.1 or current master branch @garruti9

**Comment by garruti9** [comment]
Hi @Tusamarco, 

I've checked the latest version (v1.3.1). So, if the config.toml has wrong permissions, proxysql.log file shows the message with **level=error**, as follows:

``time="2021-11-10T18:46:09Z" level=error msg="open /var/lib/proxysql/proxysql_scheduler/config/config.toml: permission denied"
``
``
time="2021-11-10T18:46:11Z" level=error msg="open /var/lib/proxysql/proxysql_scheduler/config/config.toml: permission denied"
``
``
time="2021-11-10T18:46:13Z" level=error msg="open /var/lib/proxysql/proxysql_scheduler/config/config.toml: permission denied"
``

Thanks for your quick action on this!
