### ISSUE TITLE
Deadlock proxysql with pxc_scheduler_handler

### ISSUE THREAD

**Issue by f4rx** [percona/pxc_scheduler_handler#44]
Just for information.

the problem and steps to reproduce  where described on the page https://github.com/sysown/proxysql/issues/3694

Checker send `select weight,hostname,port,comment from runtime_proxysql_servers order by weight desc` and at the same time proxysql receives information from peers which leads to a deadlock in proxysql.

**Comment by Tusamarco** [comment]
@f4rx thank you, 
I will try to recreate the issue, and see if there is anything I can do from my side to avoid the problem, also if I think this should be managed inside proxysql.

**Comment by Tusamarco** [comment]
Keeping this open as reminder but issue is managed in ProxySQL in [sysown/proxysql#3694](https://github.com/sysown/proxysql/issues/3694)

**Comment by Tusamarco** [comment]
closing this is handled in ProySQL core
