### ISSUE TITLE
Logging level warning/error still gives info logs

### ISSUE THREAD

**Issue by morganhowarth-fd** [percona/pxc_scheduler_handler#48]
Hi there,

We're in the middle of implementing this solution on our PXC clusters due to some issues around how ProxySQL native Galera support works.

I've found that when I set `logLevel` to `info` I get logs like:

```
[INFO]:2022-01-10 07:22:28 - LockerImpl initialized
[INFO]:2022-01-10 07:22:28 - Node: xx:3306 xx HG: 100 Type W coming back ONLINE from previous OFFLINE_SOFT
[INFO]:2022-01-10 07:22:28 - Node xx:3306 coming back online but will not be promoted to Writer because lower Weight 999
[INFO]:2022-01-10 07:22:28 - Processing action node list and build SQL commands
[INFO]:2022-01-10 07:22:28 - ======== Reporting execution times (nanosec/ms)by phase ============
[INFO]:2022-01-10 07:22:28 - Phase: main = 11,859,058 us 11 ms
[INFO]:2022-01-10 07:22:28 - Phase: proxysql_init = 1,805,987 us 1 ms
[INFO]:2022-01-10 07:22:28 - Phase: data_cluster_init = 9,555,889 us 9 ms
[INFO]:2022-01-10 07:22:28 - Phase: loadNodes = 3,298,413 us 3 ms
[INFO]:2022-01-10 07:22:28
```

Every time the scheduler runs (which is fine).

If I set `logLevel` to `warning` or `error` I still get info logs like this posted to the log file every time the scheduler runs:

```
[INFO]:2022-01-10 07:26:35 - Phase: main = 11,571,567 us 11 ms
[INFO]:2022-01-10 07:26:37 - Phase: main = 11,910,312 us 11 ms
[INFO]:2022-01-10 07:26:39 - Phase: main = 12,962,185 us 12 ms
[INFO]:2022-01-10 07:26:41 - Phase: main = 11,912,731 us 11 ms
```

As we ship our logs to Datadog we want to keep the logging as minimal as possible.

Is there a way to stop these info logs on warning/error?

**Comment by Tusamarco** [comment]
In the configuration file,

global section

performance= true <--- to false

------------------------------------------------
Marco Tusa,
Mobile: +1-613-282-7337
do something for your planet!
http://www.tusacentral.net/
------------------------------------------------
Save a tree... please don't print this e-mail unless you really need to

**Comment by Tusamarco** [comment]
@morganhowarth-fd 
```
In the configuration file,

global section

performance= true <--- to false
```
if this is ok please close the issue or let me know so I can close it

**Comment by morganhowarth-fd** [comment]
Thanks for the prompt reply @Tusamarco! 

I'll give it a test today, I couldn't find any documentation for `performance` and the example config file had it turned on by default so I left it as default - https://github.com/percona/pxc_scheduler_handler/blob/main/config/config.toml#L41

**Comment by morganhowarth-fd** [comment]
That did indeed fix the issue thanks! 

Closing the issue.
