### ISSUE TITLE
pxc_scheduler_handler from proxysql2 package reports wrong version

### ISSUE THREAD

**Issue by markkrj** [percona/pxc_scheduler_handler#63]
When running `pxc_scheduler_handler --version` on binary installed with proxysql2 package, it reports PoxySQL's version instead.
E.g: `PXC Scheduler Handler Version:  2.4.3`

I expected it to report only real pxc_scheduler_handler's version or both (p-s-h's and ProxySQL's).

**Comment by morganhowarth-fd** [comment]
I can also verify this running the official `percona/proxysql2` Docker image, which I'm assuming this issue also relates to:

```
docker run --rm -it percona/proxysql2 pxc_scheduler_handler --version
...
PXC Scheduler Handler Version:  2.4.4
```

Though I'm not sure if this would be an issue with the image, the `pxc_scheduler_handler`? @Tusamarco

**Comment by markkrj** [comment]
I'm using Deb packages for Ubuntu

**Comment by Tusamarco** [comment]
The version number inside the Percona distribution are unified to the proxySQL version. 
While the version number when using the tool separately is still the original.
